package cn.suvue.module.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sv_permission
 */
public class SvPermission {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   权限名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.name
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String name;

    /**
     * Database Column Remarks:
     *   类型为页面时，代表前端路由地址，类型为按钮时，代表后端接口地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.url
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String url;

    /**
     * Database Column Remarks:
     *   权限类型，页面-1，按钮-2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.type
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   权限表达式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String permission;

    /**
     * Database Column Remarks:
     *   后端接口访问方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.method
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String method;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.sort
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   父级id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_permission.parent_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.id
     *
     * @return the value of sv_permission.id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.id
     *
     * @param id the value for sv_permission.id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.name
     *
     * @return the value of sv_permission.name
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.name
     *
     * @param name the value for sv_permission.name
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.url
     *
     * @return the value of sv_permission.url
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.url
     *
     * @param url the value for sv_permission.url
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.type
     *
     * @return the value of sv_permission.type
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.type
     *
     * @param type the value for sv_permission.type
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.permission
     *
     * @return the value of sv_permission.permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.permission
     *
     * @param permission the value for sv_permission.permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.method
     *
     * @return the value of sv_permission.method
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.method
     *
     * @param method the value for sv_permission.method
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.sort
     *
     * @return the value of sv_permission.sort
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.sort
     *
     * @param sort the value for sv_permission.sort
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_permission.parent_id
     *
     * @return the value of sv_permission.parent_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_permission.parent_id
     *
     * @param parentId the value for sv_permission.parent_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}