package cn.suvue.module.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sv_role_permission
 */
public class SvRolePermission {
    /**
     * Database Column Remarks:
     *   角色主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_role_permission.role_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   权限主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_role_permission.permission_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long permissionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_role_permission.role_id
     *
     * @return the value of sv_role_permission.role_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_role_permission.role_id
     *
     * @param roleId the value for sv_role_permission.role_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_role_permission.permission_id
     *
     * @return the value of sv_role_permission.permission_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_role_permission.permission_id
     *
     * @param permissionId the value for sv_role_permission.permission_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }
}