package cn.suvue.module.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sv_user
 */
public class SvUser {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.username
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.password
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String password;

    /**
     * Database Column Remarks:
     *   昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.nickname
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   手机
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.phone
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.email
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private String email;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.birthday
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long birthday;

    /**
     * Database Column Remarks:
     *   性别，男-1，女-2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.sex
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Integer sex;

    /**
     * Database Column Remarks:
     *   状态，启用-1，禁用-0
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.status
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.create_time
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.last_update_time
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long lastUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.id
     *
     * @return the value of sv_user.id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.id
     *
     * @param id the value for sv_user.id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.username
     *
     * @return the value of sv_user.username
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.username
     *
     * @param username the value for sv_user.username
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.password
     *
     * @return the value of sv_user.password
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.password
     *
     * @param password the value for sv_user.password
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.nickname
     *
     * @return the value of sv_user.nickname
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.nickname
     *
     * @param nickname the value for sv_user.nickname
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.phone
     *
     * @return the value of sv_user.phone
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.phone
     *
     * @param phone the value for sv_user.phone
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.email
     *
     * @return the value of sv_user.email
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.email
     *
     * @param email the value for sv_user.email
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.birthday
     *
     * @return the value of sv_user.birthday
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.birthday
     *
     * @param birthday the value for sv_user.birthday
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.sex
     *
     * @return the value of sv_user.sex
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.sex
     *
     * @param sex the value for sv_user.sex
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.status
     *
     * @return the value of sv_user.status
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.status
     *
     * @param status the value for sv_user.status
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.create_time
     *
     * @return the value of sv_user.create_time
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.create_time
     *
     * @param createTime the value for sv_user.create_time
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.last_update_time
     *
     * @return the value of sv_user.last_update_time
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.last_update_time
     *
     * @param lastUpdateTime the value for sv_user.last_update_time
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setLastUpdateTime(Long lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}