package cn.suvue.module.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sv_user_role
 */
public class SvUserRole {
    /**
     * Database Column Remarks:
     *   用户主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user_role.user_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   角色主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user_role.role_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user_role.user_id
     *
     * @return the value of sv_user_role.user_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user_role.user_id
     *
     * @param userId the value for sv_user_role.user_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user_role.role_id
     *
     * @return the value of sv_user_role.role_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user_role.role_id
     *
     * @param roleId the value for sv_user_role.role_id
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}