package cn.suvue.module.mapper.example;

import cn.suvue.module.entity.SvPermission;
import cn.suvue.module.entity.SvPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    long countByExample(SvPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByExample(SvPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insert(SvPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insertSelective(SvPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    List<SvPermission> selectByExample(SvPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    SvPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") SvPermission record, @Param("example") SvPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExample(@Param("record") SvPermission record, @Param("example") SvPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByPrimaryKeySelective(SvPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByPrimaryKey(SvPermission record);
}