package cn.suvue.module.mapper.example;

import cn.suvue.module.entity.SvRolePermission;
import cn.suvue.module.entity.SvRolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    long countByExample(SvRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByExample(SvRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByPrimaryKey(@Param("roleId") Long roleId, @Param("permissionId") Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insert(SvRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insertSelective(SvRolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    List<SvRolePermission> selectByExample(SvRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") SvRolePermission record, @Param("example") SvRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_role_permission
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExample(@Param("record") SvRolePermission record, @Param("example") SvRolePermissionExample example);
}