package cn.suvue.module.mapper.example;

import cn.suvue.module.entity.SvUser;
import cn.suvue.module.entity.SvUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    long countByExample(SvUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByExample(SvUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insert(SvUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insertSelective(SvUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    List<SvUser> selectByExample(SvUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    SvUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") SvUser record, @Param("example") SvUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExample(@Param("record") SvUser record, @Param("example") SvUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByPrimaryKeySelective(SvUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByPrimaryKey(SvUser record);
}