package cn.suvue.module.mapper.example;

import cn.suvue.module.entity.SvUserRole;
import cn.suvue.module.entity.SvUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SvUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    long countByExample(SvUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByExample(SvUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int deleteByPrimaryKey(@Param("userId") Long userId, @Param("roleId") Long roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insert(SvUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int insertSelective(SvUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    List<SvUserRole> selectByExample(SvUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") SvUserRole record, @Param("example") SvUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sv_user_role
     *
     * @mbg.generated Wed Jun 02 23:11:42 CST 2021
     */
    int updateByExample(@Param("record") SvUserRole record, @Param("example") SvUserRoleExample example);
}